### PR TITLE
List React 17 as peer dependency

### PR DESCRIPTION
**Pull request by DreierF**
## What is the motivation for this pull request?

The library currently does not list React 17 as peer dependency

### CODE REVIEW

**Review by remarkablemark — CHANGES_REQUESTED** [review]
Thanks for opening this PR @DreierF! Do you mind amending the commit message so it follows the [Conventional Commits](https://www.conventionalcommits.org/) format?

```sh
git commit --amend "build(package): add react v17 to peerDependencies"
git push -f
```

This is crucial because the commit message is used to generate the release and changelog.

**Comment by remarkablemark** [comment]
You may also want to rebase with latest `master` since I fixed a CI build error in #179.

```sh
git remote add upstream https://github.com/remarkablemark/html-react-parser.git
git fetch upstream
git rebase upstream/master
```

**Comment by DreierF** [comment]
Sure. Done :)

**Review by remarkablemark — APPROVED** [review]

**Comment by remarkablemark** [comment]
Published [0.14.1](https://github.com/remarkablemark/html-react-parser/releases/tag/v0.14.1):

[npm](https://www.npmjs.com/package/html-react-parser):

```sh
npm install html-react-parser@0.14.1
```

[yarn](https://yarnpkg.com/package/html-react-parser):

```
yarn add html-react-parser@0.14.1
```

**Pull request merged**
