### PR TITLE
Add TypeScript definitions for domToReact

### LINKED ISSUE #84: Export `domToReact` in public API
Right now, if I use the `replace` option to substitute certain DOM nodes with React elements, there's no good way to keep the children of that node (to pass as children to the React element) – because the React element will expect React element children, not the DOM node objects. So the current options are:

* Turn the children back into HTML somehow and run them back through the parser in my `replace` function (wasteful).
* Reach into `html-react-parser/lib/dom-to-react` module myself (undocumented, private API).

A nicer option would be to either export `domToReact` from the main entry point, or instead of throwing on non-string inputs, assume it is already a parsed DOM tree, so you can simply do `parser(node.children)`.

### PR DESCRIPTION
**Pull request by AndrewLeedham**
### What is the motivation for this pull request?
The docs use `html-react-parser/lib/domToReact`, but TypeScript definitions only exist for the core api (`html-react-parser`). I would say this is a feature.

### Features
- TypeScript definitions exist for `html-react-parser/lib/domToReact`.
- Export `domToReact` and `htmlToDom`. (Fixes #84)

### Checklist:
- [x] Tests
- [x] Documentation (includes TSDoc comments)

### CODE REVIEW

**Comment by AndrewLeedham** [comment]
> Dependency `html-dom-parser` can now be updated to `0.2.0` so lint can pass

Hi @remarkablemark. I have been doing some testing with this today. It seems that the `types` folder structure only works for a single `index.d.ts` file. Therefore `types/lib/dom-to-react` is not recognised.

The possible solutions:
1. Move the `.d.ts` files inline with the source code, so move `dom-to-react.d.ts` to `<root>/lib/` and `index.d.ts` to `<root>/`.
2. Provide `domToReact` as an export from `index.js`.

What are your thoughts on these options? Personally I think option 1 is better, as it doesn't change the current API, and allows for other files to be exposed in TS even if they aren't necessarily part of the public facing API.

**Comment by remarkablemark** [comment]
@AndrewLeedham Thanks for looking into this and coming up with both approaches.

I'm fine with either approach and I agree that the first is cleaner. But I also do think that it may be useful to expose `domToReact` as an export on `index.js` (see #84).

Given that, would you still like me to go ahead with merging  remarkablemark/html-dom-parser#12?

**Comment by AndrewLeedham** [comment]
@remarkablemark No problem.

Perhaps we should go with a combination of the two then. Have inline `.d.ts` files and export domToReact from `index.js`.

Either way I think the `html-dom-parser` changes are required, so merging that would make sense.

**Comment by remarkablemark** [comment]
Sounds good @AndrewLeedham. [html-dom-parser@0.2.1](https://github.com/remarkablemark/html-dom-parser/tree/v0.2.1) has been published

**Comment by remarkablemark** [comment]
Thanks @AndrewLeedham for your effort and for making this possible

[0.7.0](https://github.com/remarkablemark/html-react-parser/tree/v0.7.0) has been published

**Pull request merged**
