### PR TITLE
docs(readme): change parserOptions to options in longest example

### LINKED ISSUE #122: mistake in readme example?
The longest example in README.md contains this code:

````
const options = {
  replace: ({ attribs, children }) => {
    if (!attribs) return;

    if (attribs.id === 'main') {
      return (
        <h1 style={{ fontSize: 42 }}>{domToReact(children, parserOptions)}</h1>
      );
    }

    if (attribs.class === 'prettify') {
      return (
        <span style={{ color: 'hotpink' }}>
          {domToReact(children, parserOptions)}
        </span>
      );
    }
  }
};
````

It's calling domToReact with `parserOptions` (undefined in the example) as the second option. Shouldn't that be `options`?

Thanks for a useful package!

### PR DESCRIPTION
**Pull request by dbvisel**
Changed `parserOptions` to `options` in the longest example.

Fixes #122

## Checklist:

- [x] Tests
- [x] Documentation

### CODE REVIEW

**Comment by dbvisel** [comment]
corrected the example code!

**Comment by dbvisel** [comment]
changed, I think?

**Comment by dbvisel** [comment]
pushed again! I hope this works?

**Comment by remarkablemark** [comment]
I don't think you pushed your changes. Nevertheless, I'll merge this PR since fixing the commit message is minor and a nice-to-have.

Thanks for correcting the docs @dbvisel!

**Comment by dbvisel** [comment]
oof, sorry! Trying to do too many things at once. Thanks again!

**Pull request merged**
