### PR TITLE
#625: <option> tag should also be valueOnly

### LINKED ISSUE #625: `value=` shouldn't be converted to `defaultValue=` for `<option>`
The value of `<option>` tags of `<select>` are fixed. Converting their `value=` to `defaultValue=` results bug if the option label is different from the value. For example:

```html
<select name="range" value="gte-2">
  <option value="lt-1">Less than 1</option>
  <option value="gte-2">≥2<option>
</select>
```

The value of `<select>`'s "gte-2" won't get a match and it will fallback to "Less than 1".

https://github.com/remarkablemark/html-react-parser/blob/cffffc71fe8e72e6a662de50c0b00a3d77c60cc6/lib/attributes-to-props.js#L42-L49

### PR DESCRIPTION
**Pull request by philiptzou**
Fixes #625

## Checklist:

- [x] [Conventional Commits](https://www.conventionalcommits.org/)
- [ ] Tests

### CODE REVIEW

**Review by remarkablemark — CHANGES_REQUESTED** [review]
Thanks for opening the PR @philiptzou!

Do you mind amending your commit message so it passes the linter?

```sh
git commit --amend -m "fix: option tag should also be valueOnly" -m "Fixes #625"
git push -f
```

Also, do you mind adding a test?

**Comment by philiptzou** [comment]
@remarkablemark I think this may need more works since I didn't test it. I'll work on this tomorrow.

**Comment by remarkablemark** [comment]
> @remarkablemark I think this may need more works since I didn't test it. I'll work on this tomorrow.

Sounds good 👍

**Comment by remarkablemark** [comment]
Hey @philiptzou, were you able to make any progress? Let me know if you need any help

**Comment by remarkablemark** [comment]
Closed by #790

**Pull request closed without merging**
