### PR TITLE
feat: export attributesToProps

### PR DESCRIPTION
**Pull request by cbbfcd**
## What is the motivation for this pull request?
sometimes we need custom the replacer, and so we maybe need the attributesToProps too.

## What is the current behavior?
Users need to implement it themselves

## What is the new behavior?
just require the `attributesToProps` function

## Checklist:

- [x] Tests
- [x] Documentation
- [x] Types

### CODE REVIEW

**Review by remarkablemark — CHANGES_REQUESTED** [review]
Looks good! Can you also update the `README.md` documentation with an applicable example of `attributesToProps`?

**Comment by cbbfcd** [comment]
> Looks good! Can you also update the `README.md` documentation with an applicable example of `attributesToProps`?

ok

**Review by remarkablemark — APPROVED** [review]
Looks good to me! 多谢 @cbbfcd

**Comment by remarkablemark** [comment]
Published [0.14.0](https://github.com/remarkablemark/html-react-parser/releases/tag/v0.14.0):

[npm](https://www.npmjs.com/package/html-react-parser):

```sh
npm install html-react-parser@0.14.0
```

[yarn](https://yarnpkg.com/package/html-react-parser):

```
yarn add html-react-parser@0.14.0
```

**Comment by cbbfcd** [comment]
@remarkablemark 哈哈哈哈，客气

**Pull request merged**
